-- Another requirement is to create and give all the permissions to the user so that it will be connected to this source database as Endpoint in the DMS tool. I have chosen the name MIGUSERSOURCE:

SQL>
GRANT SELECT ANY TRANSACTION to MIGUSERSOURCE;
GRANT SELECT on V_$ARCHIVED_LOG to MIGUSERSOURCE;
GRANT SELECT on V_$LOG to MIGUSERSOURCE;
GRANT SELECT on V_$LOGFILE to MIGUSERSOURCE;
GRANT SELECT on V_$DATABASE to MIGUSERSOURCE;
GRANT SELECT on V_$THREAD to MIGUSERSOURCE;
GRANT SELECT on V_$PARAMETER to MIGUSERSOURCE;
GRANT SELECT on V_$NLS_PARAMETERS to MIGUSERSOURCE;
GRANT SELECT on V_$TIMEZONE_NAMES to MIGUSERSOURCE;
GRANT SELECT on V_$TRANSACTION to MIGUSERSOURCE;
GRANT SELECT on ALL_INDEXES to MIGUSERSOURCE;
GRANT SELECT on ALL_OBJECTS to MIGUSERSOURCE;
GRANT SELECT on DBA_OBJECTS to MIGUSERSOURCE; (required if the Oracle version is earlier than
11.2.0.3)
GRANT SELECT on ALL_TABLES to MIGUSERSOURCE;
GRANT SELECT on ALL_USERS to MIGUSERSOURCE;
GRANT SELECT on ALL_CATALOG to MIGUSERSOURCE;
GRANT SELECT on ALL_CONSTRAINTS to MIGUSERSOURCE;
GRANT SELECT on ALL_CONS_COLUMNS to MIGUSERSOURCE;
GRANT SELECT on ALL_TAB_COLS to MIGUSERSOURCE;
GRANT SELECT on ALL_IND_COLUMNS to MIGUSERSOURCE;
GRANT SELECT on ALL_LOG_GROUPS to MIGUSERSOURCE;
GRANT SELECT on SYS.DBA_REGISTRY to MIGUSERSOURCE;
GRANT SELECT on SYS.OBJ$ to MIGUSERSOURCE;
GRANT SELECT on DBA_TABLESPACES to MIGUSERSOURCE;
GRANT SELECT on ALL_TAB_PARTITIONS to MIGUSERSOURCE;
GRANT SELECT on ALL_ENCRYPTED_COLUMNS to MIGUSERSOURCE;
GRANT EXECUTE ON SYS.DBMS_CRYPTO TO MIGUSERSOURCE;
